// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiltu3NSfehJtUMTFTpjKymNg63gqb1rc',
    appId: '1:51607519007:web:34fae9adf41697973f3a2a',
    messagingSenderId: '51607519007',
    projectId: 'spots-aa0e1',
    authDomain: 'spots-aa0e1.firebaseapp.com',
    storageBucket: 'spots-aa0e1.appspot.com',
    measurementId: 'G-M1C4NG8N8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzO9SJ1MTWFDBxhyg6m8S4mGngg_o6VcI',
    appId: '1:51607519007:android:1869b6fc456bc4d33f3a2a',
    messagingSenderId: '51607519007',
    projectId: 'spots-aa0e1',
    storageBucket: 'spots-aa0e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpFYWJ00aM7XrSMiS_k8Xpk38KcwtWU4',
    appId: '1:51607519007:ios:1668194eeab8bb9f3f3a2a',
    messagingSenderId: '51607519007',
    projectId: 'spots-aa0e1',
    storageBucket: 'spots-aa0e1.appspot.com',
    iosBundleId: 'com.example.flutterProjectTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpFYWJ00aM7XrSMiS_k8Xpk38KcwtWU4',
    appId: '1:51607519007:ios:1668194eeab8bb9f3f3a2a',
    messagingSenderId: '51607519007',
    projectId: 'spots-aa0e1',
    storageBucket: 'spots-aa0e1.appspot.com',
    iosBundleId: 'com.example.flutterProjectTemplate',
  );
}
